apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-new-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: maven-new-service
  template:
    metadata:
      labels:
        app: maven-new-service
    spec:
      containers:
      - image: prasanth98/maven-new-service:build-14
        name: maven-new-service
        ports:
        - containerPort: 8080
